[local_phases]
unit = "chef exec rspec"
lint = 'chef exec cookstyle --display-cop-names --extra-details'
syntax = "chef exec foodcritic . -t ~supermarket"
provision = "echo skipping"
deploy = "echo skipping"
smoke = "echo skipping"
functional = "echo skipping"
cleanup = "echo skipping"
